### ISSUE TITLE
feature:  add a just nuke it bitch response to the possible reply’s u can give

### ISSUE THREAD

**Issue by TheRavenSeb** [lawsonDevvv/ocrp-utilities#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Does this introduce any breaking changes (renaming methods, adding methods, removing things, etc)?**
Yes/No

**Comment by lawsonDevvv** [comment]
what
